### ISSUE TITLE
lorsque l'on clique sur un tag pour filtrer, ça plante

### ISSUE THREAD

**Issue by sycom** [MEEM-MLHD/dataroom#1]
problème de formation des liens : 

dans [index.html](https://github.com/MEEM-MLHD/dataroom/blob/master/index.html#L84) ligne `84` : remplacer
`<a class="ui label" href="javascript:document.getElementById('searchbox').focus();searchbox.value='<%= mywords[index] %>';FJS.filter();"><%= mywords[index] %></a>`
par
`<a class="ui label" href="#" onclick="javascript:document.getElementById('searchbox').focus();searchbox.value='<%= mywords[index] %>';FJS.filter();"><%= mywords[index] %></a>`

à répéter et adapter lignes `47` et `102`. J'ai pas testé, mais ça doit marcher. Je peux faire un PR si vous préférez...

**Comment by ouhouhsami** [comment]
Une PR ! :)
